services:
  - type: web
    name: homei-ecommerce
    env: docker
    plan: free
    region: oregon

    healthCheckPath: /

    envVars:
      - key: NODE_ENV
        value: production

      - key: RENDER
        value: true

      - key: RUN_SEEDERS
        value: false

      - key: SESSION_SECRET
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: homei-db
          property: connectionString

databases:
  - name: homei-db
    plan: free
    region: oregon
    databaseName: homei_db
    user: homei_user